"""Consumer service. One program, two behaviours.

    CONSUMER_MODE=log   exercise 1.2: log id / text / processing timestamp at a
                        controlled rate and touch nothing else.
    CONSUMER_MODE=ai    task A: call the model and store the answer.

Both modes share the delivery machinery, because that is the part the lab is
actually about: QoS, manual acknowledgement, retry routing, dead-lettering and
crash safety.

Threading: pika's BlockingConnection is not thread-safe, so this process drives
it on the main thread and nothing else touches the connection. The signal
handler cannot block in the middle of `start_consuming`, so it schedules
`stop_consuming` onto the connection's own I/O loop instead.
"""

import json
import logging
import os
import signal
import sys
import threading
import time
from typing import Any, Optional

import pika
from pika.exceptions import (
    AMQPChannelError,
    AMQPConnectionError,
    ProbableAccessDeniedError,
    ProbableAuthenticationError,
)

from . import ai_client, broker, config, store

log = logging.getLogger("consumer")

# Held so the signal handler can reach the running connection.
_ACTIVE: dict[str, Any] = {"connection": None, "channel": None}

# How many messages this process has finished, for the CRASH_AFTER_N trigger.
# Safe as a plain global: pika's BlockingConnection is driven from the main
# thread and nothing else touches it, so there is no race.
_processed = 0


def _install_signal_handlers() -> None:
    def _handle(signum, _frame):
        log.info("signal %s received, finishing current delivery then stopping",
                 signal.Signals(signum).name)
        connection = _ACTIVE["connection"]
        channel = _ACTIVE["channel"]
        if connection is not None and channel is not None and connection.is_open:
            # add_callback_threadsafe is the only safe way to touch a
            # BlockingConnection from outside its I/O loop; the callback runs on
            # the next pass, after the in-flight callback has returned.
            connection.add_callback_threadsafe(channel.stop_consuming)

    signal.signal(signal.SIGINT, _handle)
    signal.signal(signal.SIGTERM, _handle)


def _decode(body: bytes) -> dict[str, Any]:
    payload = json.loads(body.decode("utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"expected a JSON object, got {type(payload).__name__}")
    for field in ("id", "text"):
        if not payload.get(field):
            raise ValueError(f"missing required field {field!r}")
    return payload


def _attempt_of(properties: Optional[pika.BasicProperties]) -> int:
    headers = (properties.headers if properties else None) or {}
    try:
        return max(0, int(headers.get(config.RETRY_HEADER, 0)))
    except (TypeError, ValueError):
        return 0


def _maybe_crash(request_id: str, processed: int) -> None:
    """Exercise 1.3: die mid-processing so redelivery can be observed.

    Called after the work is done and before the ack, which is the only window
    that proves anything. os._exit skips interpreter cleanup, so no atexit hook
    or connection.close() can quietly acknowledge the message and hide the bug
    we are trying to show.

    Two triggers, because ids are generated by POST /process and so cannot be
    predicted in advance:

    * ``CRASH_AFTER_N`` -- die on the Nth message this process handles. This is
      the one to use; it is deterministic and needs no foreknowledge.
    * ``CRASH_AT_MESSAGE`` -- die on one specific id. Only useful if you already
      know the id, e.g. you are re-testing a redelivery by hand.
    """
    by_id = bool(config.CRASH_AT_MESSAGE) and str(request_id) == config.CRASH_AT_MESSAGE
    by_count = config.CRASH_AFTER_N > 0 and processed == config.CRASH_AFTER_N
    if not (by_id or by_count):
        return
    if by_count:
        log.error("CRASH_AFTER_N=%d reached on id=%s, simulating a crash in %.1fs",
                  config.CRASH_AFTER_N, request_id, config.CRASH_AFTER_S)
    else:
        log.error("CRASH_AT_MESSAGE=%s reached, simulating a crash in %.1fs",
                  config.CRASH_AT_MESSAGE, config.CRASH_AFTER_S)
    time.sleep(config.CRASH_AFTER_S)
    os._exit(1)


def _process(payload: dict[str, Any]) -> str:
    """Do the actual work and store the outcome. Returns the stored answer."""
    request_id = str(payload["id"])
    if config.CONSUMER_MODE == "log":
        # Exercise 1.2: hold the delivery in flight for a fixed interval so the
        # depth in the management UI visibly steps down at CONSUMER_RATE.
        if config.CONSUMER_RATE > 0:
            time.sleep(1.0 / config.CONSUMER_RATE)
        return f"logged (CONSUMER_MODE=log) at {store.utc_now()}"

    if config.AI_DELAY_S > 0:
        time.sleep(config.AI_DELAY_S)
    return ai_client.complete(payload["text"])


def _handle(channel, method, properties, body) -> None:
    """One delivery, invoked by pika on the consumer's I/O loop.

    Wrapped so that an unexpected exception dead-letters the message instead of
    tearing down the channel. A bug in this file should show up as a DLQ entry,
    not as a silently vanishing message or a crash loop.
    """
    try:
        _deliver(channel, method, properties, body)
    except Exception as exc:  # pragma: no cover - defensive
        log.exception("unhandled error processing delivery tag=%s: %s", method.delivery_tag, exc)
        if not config.AUTO_ACK:
            try:
                channel.basic_nack(delivery_tag=method.delivery_tag, requeue=False)
            except Exception:
                log.exception("could not dead-letter delivery tag=%s", method.delivery_tag)


def _deliver(channel, method, properties, body) -> None:
    attempt = _attempt_of(properties)

    try:
        payload = _decode(body)
        request_id = str(payload["id"])
    except (ValueError, UnicodeDecodeError) as exc:
        # A body we cannot parse will never parse. Retrying it three times only
        # delays the same failure, so reject it now and let the work queue's
        # x-dead-letter-exchange move it to the DLQ.
        log.error("rejecting malformed message (%s); dead-lettering", exc)
        if not config.AUTO_ACK:
            channel.basic_reject(delivery_tag=method.delivery_tag, requeue=False)
        return

    log.info("received id=%s attempt=%d redelivered=%s text=%r",
             request_id, attempt,
             "yes" if getattr(method, "redelivered", False) else "no",
             payload["text"])

    started = time.monotonic()
    try:
        answer = _process(payload)
        store.mark_completed(request_id, answer, time.monotonic() - started, attempt)
        log.info("completed id=%s in %.1fs: %s", request_id, time.monotonic() - started, answer[:120])
    except ai_client.AIError as exc:
        _settle_failure(channel, method, properties, payload, exc, attempt)
        return
    except Exception as exc:  # pragma: no cover - defensive
        log.exception("unexpected error handling id=%s", request_id)
        _settle_failure(
            channel, method, properties, payload,
            ai_client.AIError(f"unexpected: {exc}", transient=True), attempt,
        )
        return

    global _processed
    _processed += 1
    _maybe_crash(request_id, _processed)

    if not config.AUTO_ACK:
        # The only place a *successful* delivery is acknowledged. Under
        # auto_ack=True the broker already considered it delivered when it
        # arrived, which is exercise 1.3's whole lesson.
        channel.basic_ack(delivery_tag=method.delivery_tag)


def _settle_failure(channel, method, properties, payload, exc, attempt: int) -> None:
    """Retry a transient failure, dead-letter a permanent one, count either way."""
    request_id = str(payload["id"])
    transient = exc.transient
    will_retry = transient and attempt < config.MAX_RETRIES

    if transient and will_retry:
        log.warning("transient failure id=%s attempt=%d/%d: %s", request_id, attempt + 1,
                    config.MAX_RETRIES, exc)
    elif transient:
        log.error("retries exhausted id=%s after %d attempt(s): %s", request_id, attempt + 1, exc)
    else:
        log.error("permanent failure id=%s attempt=%d: %s", request_id, attempt + 1, exc)

    if config.AUTO_ACK:
        # The broker discarded this delivery the moment it arrived, so there is
        # nothing to nack and republishing a copy is the only way to keep the
        # work. Reaching this branch with a failure is itself the bug that
        # exercise 1.3a demonstrates.
        try:
            if will_retry:
                broker.publish_retry(channel, payload, properties.headers, attempt + 1)
                store.set_retries(request_id, attempt + 1)
            else:
                broker.publish_dead(channel, payload, properties.headers, reason=str(exc))
                store.mark_error(request_id, str(exc), attempt)
        except Exception as publish_exc:  # pragma: no cover - best effort
            log.error("could not republish id=%s under auto_ack: %s", request_id, publish_exc)
            store.mark_error(request_id, f"republish failed: {publish_exc}", attempt)
        return

    if will_retry:
        try:
            backoff = broker.publish_retry(channel, payload, properties.headers, attempt + 1)
        except Exception as publish_exc:
            # The retry copy never made it. Requeueing in place would spin, so
            # dead-letter it where a human can see it instead.
            log.error("could not publish retry for id=%s: %s", request_id, publish_exc)
            store.mark_error(request_id, f"retry publish failed: {publish_exc}", attempt)
            channel.basic_nack(delivery_tag=method.delivery_tag, requeue=False)
            return
        store.set_retries(request_id, attempt + 1)
        log.info("id=%s -> retry queue, backoff %dms", request_id, backoff)
        # The copy now owns the work, so this delivery is finished.
        channel.basic_ack(delivery_tag=method.delivery_tag)
        return

    store.mark_error(request_id, str(exc), attempt)
    # requeue=False hands the message to the broker, which applies the work
    # queue's x-dead-letter-exchange and routing key. Dead-lettering by hand
    # instead would leave a window where a crash between publish and ack
    # duplicates the message.
    channel.basic_nack(delivery_tag=method.delivery_tag, requeue=False)


def _consume_once(connection: pika.BlockingConnection) -> None:
    channel = connection.channel()
    broker.declare_topology(channel)
    _ACTIVE["connection"] = connection
    _ACTIVE["channel"] = channel

    channel.basic_qos(prefetch_count=config.PREFETCH_COUNT)
    channel.basic_consume(
        queue=config.QUEUE_NAME,
        on_message_callback=_handle,
        auto_ack=config.AUTO_ACK,
    )
    log.info("consuming %s (mode=%s rate=%.2f/s prefetch=%d auto_ack=%s)",
             config.QUEUE_NAME, config.CONSUMER_MODE, config.CONSUMER_RATE,
             config.PREFETCH_COUNT, config.AUTO_ACK)
    channel.start_consuming()


def run() -> int:
    store.init()
    _install_signal_handlers()
    log.info("consumer starting (mode=%s)", config.CONSUMER_MODE)
    log.info("ai=%s", ai_client.describe() if config.CONSUMER_MODE == "ai" else "disabled")
    log.info("policy: max_retries=%d retry_base=%dms queue_durable=%s persistent=%s db=%s",
             config.MAX_RETRIES, config.RETRY_BASE_MS, config.QUEUE_DURABLE,
             config.MESSAGE_PERSISTENT, config.DB_PATH)
    if config.CRASH_AFTER_N > 0:
        log.warning("CRASH_AFTER_N=%d armed; this process will os._exit(1) after "
                    "processing message number %d, before acking it",
                    config.CRASH_AFTER_N, config.CRASH_AFTER_N)
    if config.CRASH_AT_MESSAGE:
        log.warning("CRASH_AT_MESSAGE=%s armed; this process will os._exit(1) on it",
                    config.CRASH_AT_MESSAGE)

    backoff = 1.0
    while True:
        connection: Optional[pika.BlockingConnection] = None
        try:
            connection = broker.connect()
            backoff = 1.0
            _consume_once(connection)
            # A clean stop_consuming() lands here on SIGINT.
            break
        except (ProbableAuthenticationError, ProbableAccessDeniedError) as exc:
            log.error("broker rejected us: %s", exc)
            return 1
        except (AMQPConnectionError, AMQPChannelError, OSError) as exc:
            # A broker restart (exercise 1.3c) drops the socket. Reconnect
            # instead of letting the process die, otherwise the queue is left
            # with no consumer and the harness's criterion 2 waits forever.
            log.warning("broker connection lost (%s); reconnecting in %.0fs", exc, backoff)
            _sleep_unless_interrupted(backoff)
            backoff = min(backoff * 2, 30.0)
        finally:
            _ACTIVE["connection"] = None
            _ACTIVE["channel"] = None
            if connection is not None and connection.is_open:
                try:
                    connection.close()
                except Exception:  # pragma: no cover - best effort teardown
                    pass

    # Closing the channel hands any unacknowledged delivery back to the broker,
    # which is the graceful half of exercise 1.3. The ungraceful half -- no
    # chance to run any of this -- is what the harness's criterion 2 measures.
    log.info("consumer stopped; unacknowledged deliveries were requeued by the broker")
    return 0


def _sleep_unless_interrupted(seconds: float) -> None:
    threading.Event().wait(seconds)


def main() -> int:
    logging.basicConfig(
        level=os.getenv("LOG_LEVEL", "INFO").upper(),
        format="%(asctime)s %(levelname)-7s %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%S",
    )
    return run()


if __name__ == "__main__":
    sys.exit(main())
